version: '3.8'

services:
  main:
    container_name: nestjs-e2e-main
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn start:debug
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    env_file:
      - .env
    environment:
      - "DB_HOST=postgres"
      - "DB_PORT=5432"
    networks:
      - nestjs-e2e-network
    restart: unless-stopped

networks:
  nestjs-e2e-network:
    name: nestjs-e2e-network
